Tried to add tail call optimization
eregon/mozart-graal pull request #6
Opened 2016-09-24 10:32 UTC by mistasse

2016-09-24 11:04 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallThrowerNode.java
> +		throw new TailCallException(method, new Object[] { self, message });
This logic should be extracted to a different node, like `CallMethodNode`.

2016-09-24 11:05 UTC, eregon commented on src/org/mozartoz/truffle/runtime/TailCallException.java
> +public class TailCallException extends RuntimeException {
Extend ControlFlowException, so this allows the optimization in Graal.

2016-09-24 11:15 UTC, eregon commented on src/org/mozartoz/truffle/translator/Translator.java
> +		if(node instanceof TailMarkerStatement) {
missing space after the `if`, normally the Eclipse formatter should take care of this.

2016-09-24 11:25 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java
> +	@Child OzNode call;
You can type this as a CallProcNode

2016-09-24 11:27 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java
> +							);
And then reuse the CallProcNode here, with something like
`executeCall(proc, arguments)`.
But CallProcNode needs to be adapted to allow taking direct arguments and not execute the arg nodes.

2016-09-24 11:34 UTC, eregon commented on src/org/mozartoz/truffle/translator/Translator.java
> +			}
A bit of duplicated logic here.
We should probably have a `ExecuteValuesNode` that just execute a OzNode[] and returns a Object[].

2016-09-24 11:34 UTC, eregon requested changes
Looks good overall but it needs a few nicer refactorings :)

2016-09-24 16:05 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java
> +		while (true) {
There should be some profiling here, to make sure normal calls don't get overhead.

2016-09-24 20:13 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java
> +							);
> But CallProcNode needs to be adapted to allow taking direct arguments and not execute the arg nodes.

Latest master allows just that.

2016-09-25 11:12 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java
> +	BranchProfile tailCallProfile = BranchProfile.create();
Profiles must be `final` (and usually are `private` as well)

2016-09-25 11:13 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java
> +					e = exception;
Reassigning a catch variable is not too nice, could you make a tailCall local var?

2016-09-25 11:15 UTC, eregon commented on src/org/mozartoz/truffle/nodes/call/TailCallThrowerNode.java
> +	public abstract Object executeTailCall(VirtualFrame frame, Object receiver, Object[] arguments);
I think this is not needed.

2016-09-25 11:17 UTC, eregon commented on src/org/mozartoz/truffle/runtime/TailCallException.java
> +	public final Object[] arguments;
Use `@CompilationFinal(dimensions=1)` here, it allows to fold reading the elements.

2016-09-25 11:19 UTC, eregon commented on src/org/mozartoz/truffle/translator/Translator.java
> +			return new TailCallCatcherNode(translateCall((CallCommon) node));
I think this should move in `translateCall`, because all call nodes need to have the catcher.

2016-09-25 11:29 UTC, eregon commented on src/org/mozartoz/truffle/translator/Translator.java
> +			return new TailCallCatcherNode(translateCall((CallCommon) node));
Actually, move it to something like CallNode.create() and review usages of CallNodeGen.create, as they should all be wrapped with a catcher.

2016-09-25 13:21 UTC, mistasse commented on src/org/mozartoz/truffle/nodes/call/TailCallThrowerNode.java
> +	public abstract Object executeTailCall(VirtualFrame frame, Object receiver, Object[] arguments);
Do you mean the DerefNode or using the Truffle Specialization artillery? (yes, the deref should probably be done manually)

2016-09-25 14:38 UTC, eregon commented
Just this execute method is never used, is it?

On Sep 25, 2016 15:21, "Istasse Maxime" <notifications@github.com> wrote:

> *@mistasse* commented on this pull request.
> ------------------------------
>
> In src/org/mozartoz/truffle/nodes/call/TailCallThrowerNode.java
> <https://github.com/eregon/mozart-graal/pull/6>:
>
> > +
> +import com.oracle.truffle.api.dsl.CreateCast;
> +import com.oracle.truffle.api.dsl.NodeChild;
> +import com.oracle.truffle.api.dsl.NodeChildren;
> +import com.oracle.truffle.api.dsl.Specialization;
> +import com.oracle.truffle.api.frame.VirtualFrame;
> +
> +@NodeChildren({ @NodeChild("receiver"), @NodeChild("arguments") })
> +public abstract class TailCallThrowerNode extends OzNode {
> +
> +	@CreateCast("receiver")
> +	protected OzNode derefReceiver(OzNode var) {
> +		return DerefNode.create(var);
> +	}
> +
> +	public abstract Object executeTailCall(VirtualFrame frame, Object receiver, Object[] arguments);
>
> Do you mean the DerefNode or using the Truffle Specialization artillery?
> (yes, the deref should probably be done manually)
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eregon/mozart-graal/pull/6>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKTlhGqZuBdwFnBt9JHzu7o5hYcHv6xks5qtnVEgaJpZM4KFnIQ>
> .
>

2016-09-25 15:44 UTC, eregon approved these changes

2016-09-25 15:44 UTC, merged

2016-09-25 15:51 UTC, eregon commented
Congrats, works well!